### ISSUE TITLE
趋势图问题及再次上传apk后无影响

### ISSUE THREAD

**Issue by Mr-Weik** [pengchenglin/ApkChecker_new#3]
##  包大小趋势预览
首个apk解析完成后，进入到包大小趋势页面，无对应趋势图预览

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/51978319/220053367-e40f6dfc-19f6-4db2-af4d-2c09ab090de2.png">

## 再次上传apk后无响应
首次解析完成后生成对包好，点击' 上传apk'，上传文件后，网页&终端均无对应响应

## 补充：
系统：Mac os  11.6.6 (20G624)
python： 3.7 虚拟环境
<img width="602" alt="image" src="https://user-images.githubusercontent.com/51978319/220054618-35c62358-0719-49ad-8b6c-f3e902c8c4e9.png">

**Comment by chengjie04** [comment]
同样有此问题

**Comment by pengchenglin** [comment]
可能是前段css相关的资源失效了导致的 
我有时间的话看一下好了

**Comment by pengchenglin** [comment]
templates/dashboard_aab.html
templates/dashboard.html
两个文件下的18行 `<script src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>`
替换成
`<script src="https://code.highcharts.com/highcharts.js"></script>`
再试试看
国内的js访问不了了
@chengjie04  @Mr-Weik

**Comment by Mr-Weik** [comment]
> templates/dashboard_aab.html templates/dashboard.html 两个文件下的18行 替换成 再试看 国内的js访问不了了`<script src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>` `<script src="https://code.highcharts.com/highcharts.js"></script>` @chengjie04 @Mr-Weik

好的，明天尝试后反馈，感谢

**Comment by Mr-Weik** [comment]
> templates/dashboard_aab.html templates/dashboard.html 两个文件下的18行 `<script src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>` 替换成 `<script src="https://code.highcharts.com/highcharts.js"></script>` 再试试看 国内的js访问不了了 @chengjie04 @Mr-Weik

可以了，👍
